In [3]:
import numpy as np
import pandas as pd
import urllib


In [36]:
df=pd.read_csv('dataset.csv',header=None,sep=',')
df = np.array(df)
X = df[:,0:7]
y = df[:,8]

In [39]:
from sklearn import preprocessing
# normalize the data attributes
normalized_X = preprocessing.normalize(X)
# standardize the data attributes
standardized_X = preprocessing.scale(X)

In [40]:
#特征选择
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(X, y)
# display the relative importance of each attribute
print(model.feature_importances_)

[ 0.12390788  0.27757572  0.11867507  0.09980847  0.08708251  0.1546408
  0.13830955]


In [41]:
#特征工程
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(X, y)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[ True False False False False  True  True]
[1 2 3 5 4 1 1]


In [42]:
#逻辑回归
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
             precision    recall  f1-score   support

        0.0       0.79      0.89      0.84       500
        1.0       0.74      0.55      0.63       268

avg / total       0.77      0.77      0.77       768

[[447  53]
 [120 148]]


In [43]:
#朴素贝叶斯
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

GaussianNB(priors=None)
             precision    recall  f1-score   support

        0.0       0.80      0.86      0.83       500
        1.0       0.69      0.60      0.64       268

avg / total       0.76      0.77      0.76       768

[[429  71]
 [108 160]]


In [10]:
#knn
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
             precision    recall  f1-score   support

        0.0       0.83      0.88      0.85       500
        1.0       0.75      0.65      0.70       268

avg / total       0.80      0.80      0.80       768

[[442  58]
 [ 93 175]]


In [47]:
#决策树
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
# fit a CART model to the data
model = DecisionTreeClassifier()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       500
        1.0       1.00      1.00      1.00       268

avg / total       1.00      1.00      1.00       768

[[500   0]
 [  0 268]]


In [8]:
#svm
from sklearn import metrics
from sklearn.svm import SVC
# fit a SVM model to the data
model = SVC()
model.fit(X_train, y_train)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
model.score(X_test, y_test)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


0.66233766233766234

In [5]:
#读取数据，以逗号隔开的csv文件
dataset = pd.read_csv('dataset.csv', header=None, sep=',')
dataset = np.array(dataset)
X_len = len(dataset[0]) - 1
X = dataset[:,:X_len]

y = dataset[:,X_len:].reshape(-1,)

In [103]:
X.shape, y.shape

((768, 8), (768,))

In [104]:
#交叉验证
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=7)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [17]:
#数据分割
from sklearn import cross_validation
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.05)

In [18]:
#训练
clf = KNeighborsClassifier().fit(X_train, y_train)
expected = y
predicted = clf.predict(X)
print(metrics.classification_report(expected, predicted))
score = clf.score(X_test, y_test)


             precision    recall  f1-score   support

        0.0       0.82      0.87      0.85       500
        1.0       0.74      0.65      0.69       268

avg / total       0.79      0.80      0.79       768



0.79487179487179482

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import metrics
from sklearn import cross_validation
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

D:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [14]:
#选择文件
filename = input('输入训练数据文件')
dataset = pd.read_csv(filename, header=None, sep=',')
dataset = np.array(dataset)
X_len = len(dataset[0]) - 1
X = dataset[:,:X_len]
y = dataset[:,X_len:].reshape(-1,)

输入训练数据文件dataset.csv


In [15]:
#标准化
scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.1)

In [16]:
clf_logreg = LogisticRegression()
clf_nvby = GaussianNB()
clf_knn = KNeighborsClassifier()
clf_tree = DecisionTreeClassifier()
clf_svm = SVC()
clf = clf_tree
clf.fit(X_train,y_train)
#expected = y
#predicted = clf.predict(X)
#print(metrics.classification_report(expected, predicted))
score = clf.score(X_test, y_test)
print(r'准确率:',score)
#print(predicted)

准确率: 0.805194805195


In [17]:
testname = input('输入预测文件')
preset = pd.read_csv(testname, header=None, sep=',')
x = np.array(preset)
predicted = clf.predict(x)
x = pd.DataFrame(x)
predicted = pd.DataFrame(predicted)
res = pd.concat([x, predicted], axis=1)
res.to_csv('res.csv',index=False,header=None)

输入预测文件test.csv


In [31]:
import string
import random

def gencode(nums, lens):
    pool = list(string.ascii_uppercase)
    result = {}
    while len(result)<nums:
        key = ''
        for i in range(lens):
            key += random.choice(pool)
        if key not in result:
            result[key] = 1
    return [key for key in result]
print(gencode(4,5))

['BUTRP', 'OSRKI', 'PXZXU', 'DERHU']


In [30]:
from PIL import Image, ImageFont, ImageDraw
#import matplotlib as mpl
#import matplotlib.pyplot as plt
#import matplotlib.image as mpimg

font = ImageFont.truetype('cambriaz.ttf', 54)
img = Image.open(r'1.jpg')
draw = ImageDraw.Draw(img)
draw.text((img.size[0]*0.85, img.size[1]*0.05), u'5', font=font, fill=(255,0,0))
img.save('2.jpg')
#lena = mpimg.imread('2.jpg')
#plt.imshow(lena)
#plt.show()

In [2]:
import mysql.connector

def code2sql():
    db = mysql.connector.connect(user='',password='',host='',database='')
    cur = db.cursor()
    cur.execute("drop table if exists acode")
    cur.execute('create acode(id int primary key, code varchar(20))')
    for key in gencode(4,5):
        cur.execute("insert into acode(code) values('%s')",key)
    cur.close()

ModuleNotFoundError: No module named 'mysql'

In [7]:
import re
from collections import Counter

def countwd(filename):
    txt = open(filename,'r').read().lower()
    pat = r'[a-zA-Z-]+'
    words = re.findall(pat,txt)
    return(Counter(words).items())

In [8]:
from PIL import Image
import os

def changephsize(oldir,weight,height,newdir):
    photos = os.listdir(oldir)
    for photo in photos:
        phpath = os.path.join(oldir,photo)
        if os.path.isfile(phpath):
            im = Image.open(phpath)
            newim = im.resize((weight,height))
            newpath = os.path.join(newdir,photo)
            newim.save(newpath)

In [33]:
import os

def countcode(path):
    common_lines = 0
    code_lines = 0
    for root, dirs,files in os.walk(path):
        for file in files:
            file_abs_path = os.path.join(root,file)
            if os.path.splitext(file_abs_path)[1] == '.py':
                with open(file_abs_path,'rb') as f:
                    while True:
                        line = f.readline().decode('utf-8')
                        if not line:
                            break
                        elif line.strip().startswith('#'):
                            common_lines += 1
                        elif line.strip().startswith("'''") or line.strip().startswith('"""'):
                            common_lines += 1
                            if line.count('"""') ==1 or line.count("'''") ==1:
                                while True:
                                    line = fp.readline()
                                    common_lines += 1
                                    if ("'''" in line) or ('"""' in line):
                                        break
                        elif line.strip():
                            code_lines += 1
    return common_lines, code_lines

(8, 36)

In [43]:
from bs4 import BeautifulSoup

def partext(path):
    text = []
    url = []
    with open(path,encoding='utf-8') as f:
        html = BeautifulSoup(f, 'html.parser')
        content = html.select('.content p')
        for p in content:
            text.append(p.text)
        href = html.find_all('a')
        for each in href:  
            if str(each.get('href'))[:4]=='http':  
                url.append(each.get('href'))
        
        return text,url

In [58]:
from PIL import Image,ImageFont,ImageDraw,ImageFilter
import random
 
 
#返回随机字母
def charRandom():
    return chr((random.randint(65,90)))
 
#返回随机数字
def numRandom():
    return random.randint(0,9)
 
#随机颜色
def colorRandom1():
    return (random.randint(64,255),random.randint(64,255),random.randint(64,255))
 
#随机长生颜色2
def colorRandom2():
    return (random.randint(32,127),random.randint(32,127),random.randint(32,127))
 
width = 60 * 4
height = 60
image = Image.new('RGB', (width,height), (255,255,255));
#创建font对象
font = ImageFont.truetype('cambriaz.ttf',36);
 
#创建draw对象
draw = ImageDraw.Draw(image)
#填充每一个颜色
for x in range(width):
    for y in range(height):
        draw.point((x,y), fill=colorRandom1())
         
#输出文字
for t in range(4):
    draw.text((60*t+10,10), charRandom(),font=font, fill=colorRandom2())
 #模糊
image = image.filter(ImageFilter.BLUR)
image.show()

In [3]:
def filterwords():
    words = set('')
    f = open('filtered_words.txt', 'rb')
    for l in f.readlines():
        words.add(l.strip().decode('utf-8'))
    f.close()
    w = input('enter your words: ')
    if w in words:
        print('Freedom')
    else:
        print('Human Rights')
filterwords()

enter your words: love
Freedom


In [10]:
def filterwords(iw):
    words =[]
    file = open('filtered_words.txt', 'rb')
    for f in file.readlines():
        words.append(f.decode('utf-8'))
    file.close()
    for i in range(len(words)):
        word = words[i].strip()
        if iw.find(word) > -1:
            return word
    return ''


iw = input('enter your words: ')
word = filterwords(iw)
if word != '':
    print(iw.replace(word, '***'))
else:
    print(iw)

enter your words: 我love北京
我love***


In [25]:
def replaced():
    w = input()
    words = []
    file = open('filtered_words.txt', 'rb')
    for line in file.readlines():
        words.append(line.strip().decode('utf-8'))
    file.close()
    for word in words:
        if word in w:
            w = w.replace(word, '**')
    return w
replaced()

我love北京


'我****'

In [2]:
#14
import json 
import os
import xlwt

def wxl():
    with open(r'student.txt') as f:
        content = f.read()
    j = json.loads(content)
    file = xlwt.Workbook()
    table = file.add_sheet('test')
    for row, i in enumerate(list(d)):
        table.write(row, 0, i)
        for col, j in enumerate(d[i]):
            table.write(row, col+1, j)
    file.save('student.xls')

In [1]:
import xlwt
import json

def wtxl():
    with open(r'city.txt') as f:
        content = f.read()
    j = json.load(content)
    file = xlwt.Workbook()
    table = file.add_sheet('city')
    for row, i in enumerate(list(d)):
        table.write(row, 0, i)
        table.write(row, 1, d[i])
    file.save('city.xls')

In [4]:
def wlxl():
    with open(r'num.txt') as f:
        content = f.read()
    j = json.load(content)
    file = xlwt.Workbook()
    table = file.add_sheet('city')
    for row, i in enumerate(d):
        for col,j in enumerate(i):
            table.write(row, col, j)
    file.save('num.xls')

In [96]:
import requests
from bs4 import BeautifulSoup

def down():
    url ="http://tieba.baidu.com/p/2166231880"
    save_path = 'pic'
    html = requests.get(url)
    soup = BeautifulSoup(html.text,'html.parser')
    picl = soup.select('.BDE_Image')
    counter = 1
    for pl in picl:
        urlp = pl.get('src')
        pic = requests.get(urlp).content
        postfix = urlp[urlp.rfind('.'):]
        file = open(r'pic/'+save_path+str(counter)+postfix,'wb')
        try:
            file.write(pic)
        finally:
            file.close()
        counter += 1
    print('下载了：%d张'%counter)

In [25]:
from tkinter import *
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import metrics
from sklearn import cross_validation
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
import tkinter.messagebox as messagebox
from tkinter.filedialog import askdirectory
from sklearn.model_selection import cross_val_score
from sklearn.externals import joblib

class Application(Frame):
    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.grid()
        self.createWidgets()
            

    #页面布局
    def createWidgets(self):
        self.fileLabel = Label(self, text='文件地址：')
        self.fileLabel.grid(row=0, sticky=W)
        self.filePath = Entry(self, textvariable = path)
        self.filePath.grid(row=0, column=1, sticky=W)
        self.fileButton = Button(self, text='提交', command=self.choic)
        self.fileButton.grid(row=0, column=2, sticky=W)
        #self.selectButton = Button(self, text='选择文件', command=self.selectPath)
        #self.selectButton.grid(row=0, column=2, sticky=W)
        self.fileLabel = Label(self, text='选择分类算法：')
        self.fileLabel.grid(row=1, sticky=W)
        self.var = IntVar()
        self.reg = Radiobutton(self, text='逻辑回归',variable = self.var, value='1')
        self.reg.grid(row=1, column=1)
        self.nvby = Radiobutton(self, text='朴素贝叶斯',variable = self.var, value='2')
        self.nvby.grid(row=1, column=2, sticky=W)
        self.knn = Radiobutton(self, text='K近邻', variable = self.var, value='3')
        self.knn.grid(row=1, column=3, sticky=W)
        self.tree = Radiobutton(self, text='决策树', variable = self.var, value='4')
        self.tree.grid(row=1, column=4, sticky=W)
        self.svm = Radiobutton(self, text='支持向量机', variable = self.var, value='5')
        self.svm.grid(row=1, column=5, sticky=W)
        self.alertButton = Button(self, text='提交', command=self.learn)
        self.alertButton.grid(row=3, column=1)
        self.predictLabel = Label(self, text='预测文件地址：')
        self.predictLabel.grid(row=6, sticky=W)
        self.predictPath = Entry(self, textvariable = path)
        self.predictPath.grid(row=6,column=1,sticky=W) 
        self.predictButton = Button(self, text='提交', command=self.pred)
        self.predictButton.grid(row=7,column=1)
    
    def selectPath(self):
        #路径选择
        path.set(askdirectory())
    
    def choic(self):
        value = self.var.get() or '2'
        #if value == 1:
            #clf = LogisticRegression()
        #elif value == 2:
            #clf =  GaussianNB()
        #elif value == 3:
            #clf = KNeighborsClassifier()
        #elif value == 4:
            #clf = DecisionTreeClassifier()
        elif value == 5:
            self.fiveLabel = Label(self, text='选择核函数与罚数')
            self.fiveLabel.grid(row=4, sticky=W)
            self.fiveText = Entry(self)
            self.fiveText.grid(row=4, column=1, sticky=W)
        
    def learn(self):
        
        #选择分类算法
        value = self.var.get() or '2'
        if value == 1:
            clf = LogisticRegression()
        elif value == 2:
            clf =  GaussianNB()
        elif value == 3:
            clf = KNeighborsClassifier()
        elif value == 4:
            clf = DecisionTreeClassifier()
        elif value == 5:
            clf = SVC()
        #数据预处理
        filename = self.filePath.get()
        dataset = pd.read_csv(filename, header=None, sep=',')
        dataset = np.array(dataset)
        X_len = len(dataset[0]) - 1
        X = dataset[:,:X_len]
        y = dataset[:,X_len:].reshape(-1,)
        scaler = preprocessing.StandardScaler().fit(X)
        X = scaler.transform(X)
        X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.1)
        #训练
        clf.fit(X_train,y_train)
        joblib.dump(clf, 'clf.model')
        #score = cross_val_score(clf, X_test, y_test, cv = 10, scoring='accuracy', n_jobs=-1).mean()
        score = clf.score(X_test, y_test)
        messagebox.showinfo('准确率','准确率： %s' % score)
        
        
    def pred(self):
        testname = self.predictPath.get()
        preset = pd.read_csv(testname, header=None, sep=',')
        x = np.array(preset)
        predicted = clf.predict(x)
        x = pd.DataFrame(x)
        predicted = pd.DataFrame(predicted)
        res = pd.concat([x, predicted], axis=1)
        res.to_csv('res.csv',index=False,header=None)
        messagebox.showinfo('完成','预测完成，已保存到res.csv')
app = Application()
# 设置窗口标题:
app.master.title('分类器')
# 主消息循环:
app.mainloop()

In [1]:
D:\Jupyter\gluon\chapter_convolutional-neural-networks\submission.csv

Object `cross_val_score` not found.


In [45]:
clf_logreg = LogisticRegression()
clf_nvby = GaussianNB()
clf_knn = KNeighborsClassifier()
clf_tree = DecisionTreeClassifier()
clf_svm = SVC()

In [2]:
from tkinter import *
from tkinter.filedialog import askdirectory
import tkinter.messagebox as messagebox

def selectPath():
    filePath = askdirectory()
    path.set(filePath)
def pr():
    messagebox.showinfo('准确率：%s' % path.get())

root = Tk()
path = StringVar()

Label(root,text = "目标路径:").grid(row = 0, column = 0)
te = Entry(root, textvariable = path)
te.grid(row = 0, column = 1)
Button(root, text = "路径选择", command = selectPath).grid(row = 0, column = 2)
alertButton = Button(root, text='提交', command=pr)
alertButton.grid(row=3, column=1)

root.mainloop()

In [14]:
testname = input('输入预测文件')
preset = pd.read_csv(testname, header=None, sep=',')
x = np.array(preset)
predicted = clf.predict(x)
x = pd.DataFrame(x)
predicted = pd.DataFrame(predicted)
res = pd.concat([x, predicted], axis=1)
res.to_csv('res.csv',index=False,header=None)