In [3]:
import numpy as np
import pandas as pd
import urllib


In [36]:
df=pd.read_csv('dataset.csv',header=None,sep=',')
df = np.array(df)
X = df[:,0:7]
y = df[:,8]

In [39]:
from sklearn import preprocessing
# normalize the data attributes
normalized_X = preprocessing.normalize(X)
# standardize the data attributes
standardized_X = preprocessing.scale(X)

In [40]:
#特征选择
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(X, y)
# display the relative importance of each attribute
print(model.feature_importances_)

[ 0.12390788  0.27757572  0.11867507  0.09980847  0.08708251  0.1546408
  0.13830955]


In [41]:
#特征工程
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(X, y)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[ True False False False False  True  True]
[1 2 3 5 4 1 1]


In [42]:
#逻辑回归
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
             precision    recall  f1-score   support

        0.0       0.79      0.89      0.84       500
        1.0       0.74      0.55      0.63       268

avg / total       0.77      0.77      0.77       768

[[447  53]
 [120 148]]


In [43]:
#朴素贝叶斯
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

GaussianNB(priors=None)
             precision    recall  f1-score   support

        0.0       0.80      0.86      0.83       500
        1.0       0.69      0.60      0.64       268

avg / total       0.76      0.77      0.76       768

[[429  71]
 [108 160]]


In [10]:
#knn
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
             precision    recall  f1-score   support

        0.0       0.83      0.88      0.85       500
        1.0       0.75      0.65      0.70       268

avg / total       0.80      0.80      0.80       768

[[442  58]
 [ 93 175]]


In [47]:
#决策树
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
# fit a CART model to the data
model = DecisionTreeClassifier()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       500
        1.0       1.00      1.00      1.00       268

avg / total       1.00      1.00      1.00       768

[[500   0]
 [  0 268]]


In [8]:
#svm
from sklearn import metrics
from sklearn.svm import SVC
# fit a SVM model to the data
model = SVC()
model.fit(X_train, y_train)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
model.score(X_test, y_test)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


0.66233766233766234

In [5]:
#读取数据，以逗号隔开的csv文件
dataset = pd.read_csv('dataset.csv', header=None, sep=',')
dataset = np.array(dataset)
X_len = len(dataset[0]) - 1
X = dataset[:,:X_len]

y = dataset[:,X_len:].reshape(-1,)

In [103]:
X.shape, y.shape

((768, 8), (768,))

In [104]:
#交叉验证
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=7)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [17]:
#数据分割
from sklearn import cross_validation
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.05)

In [18]:
#训练
clf = KNeighborsClassifier().fit(X_train, y_train)
expected = y
predicted = clf.predict(X)
print(metrics.classification_report(expected, predicted))
score = clf.score(X_test, y_test)


             precision    recall  f1-score   support

        0.0       0.82      0.87      0.85       500
        1.0       0.74      0.65      0.69       268

avg / total       0.79      0.80      0.79       768



0.79487179487179482

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import metrics
from sklearn import cross_validation
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

D:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [13]:
#选择文件
filename = input('输入训练数据文件')
dataset = pd.read_csv(filename, header=None, sep=',')
dataset = np.array(dataset)
X_len = len(dataset[0]) - 1
X = dataset[:,:X_len]
y = dataset[:,X_len:].reshape(-1,)

输入训练数据文件dataset.csv


In [14]:
#标准化
scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.1)

In [16]:
clf_logreg = LogisticRegression()
clf_nvby = GaussianNB()
clf_knn = KNeighborsClassifier()
clf_tree = DecisionTreeClassifier()
clf_svm = SVC()
clf = clf_tree
clf.fit(X_train,y_train)
#expected = y
#predicted = clf.predict(X)
#print(metrics.classification_report(expected, predicted))
score = clf.score(X_test, y_test)
print(r'准确率:',score)
#print(predicted)

准确率: 0.74025974026


In [18]:
testname = input('输入预测文件')
preset = pd.read_csv(testname, header=None, sep=',')
x = np.array(preset)
predicted = clf.predict(x)
x = pd.DataFrame(x)
predicted = pd.DataFrame(predicted)
res = pd.concat([x, predicted], axis=1)
res.to_csv('res.csv',index=False,header=None)

输入预测文件test.csv
